/// *************************Board*************************

### postboard
POST http://localhost:8080/api/board
Content-Type: application/json

{
  "value": "CBSE"
}

### getboards
GET http://localhost:8080/api/board

### getboardByID
GET http://localhost:8080/api/board/1

// **************************Category**************************

### postcategory
POST http://localhost:8080/api/category
Content-Type: application/json

{
  "value": "SC"
}

### getcategories
GET http://localhost:8080/api/category

### getcategorybyId
GET http://localhost:8080/api/category/2

// **************************family**************************

### postfamily
POST http://localhost:8080/api/family
Content-Type: application/json

{
  "father_name": "NK",
  "mother_name": "MR",
  "father_occupation_id": 1,
  "mother_occupation_id": 1,
  "address": "Kathmandu",
  "city": "Kathmandu",
  "state": "Bagmati",
  "zip": "444444",
  "tenth_year": 2016,
  "tenth_percentage": 88.88,
  "tenth_board_id": 1,
  "twelfth_year": 2018,
  "twelfth_percentage": 74.6,
  "twelfth_board_id": 1
}

### getfamilies
GET http://localhost:8080/api/family

### get_family_by_id
GET http://localhost:8080/api/family/1

// ********************Father_occupation**************************

### postfatheroccupation
POST http://localhost:8080/api/father_occupation
Content-Type: application/json

{
  "value": "Bussiness"
}

### getcategories
GET http://localhost:8080/api/father_occupation

### getfatheroccupationbyId
GET http://localhost:8080/api/father_occupation/1

// ********************Gender*************************

### postgender
POST http://localhost:8080/api/gender
Content-Type: application/json

{
  "value": "Female"
}

### getgenders
GET http://localhost:8080/api/gender

### getgenderByID
GET http://localhost:8080/api/gender/1

// ********************Mother_occupation**************************

### postmotheroccupation
POST http://localhost:8080/api/mother_occupation
Content-Type: application/json

{
  "value": "Teacher"
}

### getcategories
GET http://localhost:8080/api/mother_occupation

### getmotheroccupationbyId
GET http://localhost:8080/api/mother_occupation/1

// ********************Pesonal*************************
### postpersonal
POST http://localhost:8080/api/personal
Content-Type: application/json

{
  "firstname": "Nabin",
  "lastname": "Karki",
  "email": "nabin@karki.com",
  "phone": "9876543210",
  "dob": "2018-01-01",
  "gender_id": 1,
  "category_id": 1,
  "ug_qualification_id": 1,
  "ug_specialization_id": 1,
  "ug_startyear": 2018,
  "ug_endyear": 2022,
  "ug_cgpa": 7.78
}

### getpersonals
GET http://localhost:8080/api/personal

### getpersonalbyId
GET http://localhost:8080/api/personal/1

// ********************PG *************************

### postpg
POST http://localhost:8080/api/pg
Content-Type: application/json

{
  "qualification_id": 2,
  "specialization_id": 2,
  "startyear": 2023,
  "endyear": 2025,
  "cgpa": 8
}

### getcategories
GET http://localhost:8080/api/pg

### getpgbyId
GET http://localhost:8080/api/pg/1

// ********************Qualification**************************

### postqualification
POST http://localhost:8080/api/qualification
Content-Type: application/json

{
  "value": "MBA"
}

### getcategories
GET http://localhost:8080/api/qualification

### getqualificationbyId
GET http://localhost:8080/api/qualification/1

// ********************Specialization**************************

### postspecialization
POST http://localhost:8080/api/specialization
Content-Type: application/json

{
  "value": "General"
}

### getcategories
GET http://localhost:8080/api/specialization

### getspecializationbyId
GET http://localhost:8080/api/specialization/1