//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub mod prelude;

pub mod board;
pub mod category;
pub mod family;
pub mod father_occupation;
pub mod gender;
pub mod mother_occupation;
pub mod personal;
pub mod pg;
pub mod qualification;
pub mod seaql_migrations;
pub mod specialization;
pub mod student;
