//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::board::Entity as Board;
pub use super::category::Entity as Category;
pub use super::family::Entity as Family;
pub use super::father_occupation::Entity as FatherOccupation;
pub use super::gender::Entity as Gender;
pub use super::mother_occupation::Entity as MotherOccupation;
pub use super::personal::Entity as Personal;
pub use super::pg::Entity as Pg;
pub use super::qualification::Entity as Qualification;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::specialization::Entity as Specialization;
pub use super::student::Entity as Student;
pub use super::teacher::Entity as Teacher;
